services:
  sglang:
    image: sglang-custom:cu129
    container_name: sglang
    shm_size: 32g
    ports:
      - 30000:30000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: always
    # network_mode: host # required by RDMA
    # privileged: true # required by RDMA
    environment:
      - HF_TOKEN=${HF_TOKEN}
    entrypoint: python3 -m sglang.launch_server
    command: --model-path meta-llama/Llama-3.1-8B-Instruct
      --host 0.0.0.0
      --port 30000
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:30000/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
